# Generated by Django 2.0.5 on 2018-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='movie_images',
            field=models.ImageField(default='accounts/images/default_poster.jpg', upload_to='accounts/images'),
        ),
    ]
