# Generated by Django 2.0.5 on 2018-05-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_item_movie_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='movie_images',
            new_name='poster',
        ),
    ]
