# Generated by Django 2.0.5 on 2018-05-11 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180511_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number !!!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
