# Generated by Django 2.0.5 on 2018-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180511_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Action'), ('B', 'Adventure'), ('C', 'Sci-Fi')], max_length=1),
        ),
    ]
