# Generated by Django 2.0.5 on 2018-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180514_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Action'), ('B', 'Adventure'), ('C', 'Sci-Fi')], default='A', max_length=1),
        ),
    ]
