# Generated by Django 2.0.5 on 2018-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180514_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure')], max_length=2),
        ),
    ]
