# Generated by Django 2.0.5 on 2018-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180514_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documentary'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('HO', 'Horror'), ('MR', 'Mystery'), ('SC', 'Sci_Fi')], max_length=2),
        ),
    ]
