# Generated by Django 2.0.5 on 2018-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180515_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('Comedy', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documentary'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('HO', 'Horror'), ('MR', 'Mystery'), ('SC', 'Sci_Fi')], max_length=2),
        ),
    ]
